import React from 'react';
import { render } from 'react-dom';
import './style.css';

const App = () => (
  <div className="container">
    <header>
      <div className="logo"></div>
      <h1>React web application</h1>
    </header>
    <main>
      <p>React starter kit generated by <a href="https://www.npmjs.com/package/whipapp">whipapp</a></p>
    </main>
  </div>
);

render(<App />, document.querySelector('#app'));
